#!/usr/bin/python

import boto3
import json

# Create a bucket policy
s3 = boto3.client('s3')
response = s3.create_bucket(
    ACL='public-read-write',
    Bucket='gov-cl-acesslog',
    )

response = s3.create_bucket(
    ACL='public-read-write',
    Bucket='gov-cl-target-bkt',
    )

bucket_name = 'gov-cl-acesslog'

# Create the bucket policy
bucket_policy = {
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "AWSCloudTrailAclCheck20150319",
            "Effect": "Allow",
            "Principal": {"Service": "cloudtrail.amazonaws.com"},
            "Action": "s3:GetBucketAcl",
            "Resource": "arn:aws:s3:::gov-cl-acesslog"
        },
        {
            "Sid": "AWSCloudTrailWrite20150319",
            "Effect": "Allow",
            "Principal": {"Service": "cloudtrail.amazonaws.com"},
            "Action": "s3:PutObject",
            "Resource": "arn:aws:s3:::gov-cl-acesslog/*",
            "Condition": {"StringEquals": {"s3:x-amz-acl": "bucket-owner-full-control"}}
        }
    ]
}

# Convert the policy to a JSON string
bucket_policy = json.dumps(bucket_policy)

# Set the new policy on the given bucket
s3.put_bucket_policy(Bucket=bucket_name, Policy=bucket_policy)

#================================================================CLOUD TRAIL==================================================

cTrail   = boto3.client('cloudtrail')
response2 = cTrail.describe_trails()
print (response2)

cTrail.create_trail(
    Name='govs-access-log',
    S3BucketName=bucket_name,
    IncludeGlobalServiceEvents=True,
    IsMultiRegionTrail=True,
)

#===========================================================Enable Access Log===============================================
log_response = s3.put_bucket_logging(
    Bucket='gov-cl-acesslog',
    BucketLoggingStatus={
        'LoggingEnabled': {
            'TargetBucket': 'gov-cl-target-bkt',
            'TargetPrefix': 'none'
        }
    },

)



log_response = s3.put_bucket_logging(
    Bucket='gov-cl-acesslog',
    BucketLoggingStatus={
        'LoggingEnabled': {
            'TargetBucket': 'gov-cl-target-bkt',
            'TargetGrants': [
                {
                    'Grantee': {
#                        'DisplayName': 'string',
#                        'EmailAddress': 'string',
#                        'ID': 'string',
                        'Type': 'Group',
                        'URI': "http://acs.amazonaws.com/groups/s3/LogDelivery"
                    },
                    'Permission': 'FULL_CONTROL',
                },
            ],
            'TargetPrefix': 'none'
        }
    },

)
